#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

if env["vulkan"]:
    env.add_source_files(env.editor_sources, "shader_baker_export_plugin_platform_vulkan.cpp")

if env.get("d3d12", False):
    env.add_source_files(env.editor_sources, "shader_baker_export_plugin_platform_d3d12.cpp")

if env.get("metal", False):
    env.add_source_files(env.editor_sources, "shader_baker_export_plugin_platform_metal.cpp")
